/*
Gridly API

Testing ProjectApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package gridly

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    gridly "./openapi"
)

func Test_gridly_ProjectApiService(t *testing.T) {

    configuration := gridly.NewConfiguration()
    apiClient := gridly.NewAPIClient(configuration)

    t.Run("Test ProjectApiService Create", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.ProjectApi.Create(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ProjectApiService Delete", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var projectId int64

        resp, httpRes, err := apiClient.ProjectApi.Delete(context.Background(), projectId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ProjectApiService FindOne", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var projectId int64

        resp, httpRes, err := apiClient.ProjectApi.FindOne(context.Background(), projectId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ProjectApiService List", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.ProjectApi.List(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ProjectApiService Update", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var projectId int64

        resp, httpRes, err := apiClient.ProjectApi.Update(context.Background(), projectId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
