/*
Gridly API

Testing AutomationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package gridly

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	gridly "github.com/gridly-spreadsheet-CMS/gridly-go-sdk"
)

func Test_gridly_AutomationAPIService(t *testing.T) {

	configuration := gridly.NewConfiguration()
	apiClient := gridly.NewAPIClient(configuration)

	t.Run("Test AutomationAPIService BulkTrigger", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AutomationAPI.BulkTrigger(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AutomationAPIService Get", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var automationId string

		resp, httpRes, err := apiClient.AutomationAPI.Get(context.Background(), automationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AutomationAPIService GetExecution", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var automationId string
		var executionId string

		resp, httpRes, err := apiClient.AutomationAPI.GetExecution(context.Background(), automationId, executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AutomationAPIService GetExecutions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var automationId string

		resp, httpRes, err := apiClient.AutomationAPI.GetExecutions(context.Background(), automationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AutomationAPIService List", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AutomationAPI.List(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AutomationAPIService Trigger", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var automationId string

		resp, httpRes, err := apiClient.AutomationAPI.Trigger(context.Background(), automationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
