/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateProject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProject{}

// UpdateProject struct for UpdateProject
type UpdateProject struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
}

type _UpdateProject UpdateProject

// NewUpdateProject instantiates a new UpdateProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProject(name string) *UpdateProject {
	this := UpdateProject{}
	this.Name = name
	return &this
}

// NewUpdateProjectWithDefaults instantiates a new UpdateProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProjectWithDefaults() *UpdateProject {
	this := UpdateProject{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateProject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateProject) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateProject) SetName(v string) {
	o.Name = v
}


// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateProject) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProject) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateProject) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateProject) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateProject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *UpdateProject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varUpdateProject := _UpdateProject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProject)

	if err != nil {
		return err
	}

	*o = UpdateProject(varUpdateProject)

	return err
}

type NullableUpdateProject struct {
	value *UpdateProject
	isSet bool
}

func (v NullableUpdateProject) Get() *UpdateProject {
	return v.value
}

func (v *NullableUpdateProject) Set(val *UpdateProject) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProject) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProject(val *UpdateProject) *NullableUpdateProject {
	return &NullableUpdateProject{value: val, isSet: true}
}

func (v NullableUpdateProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


