/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Formula type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Formula{}

// Formula struct for Formula
type Formula struct {
	FormulaText string `json:"formulaText"`
	AlwaysFormatResultValueAsList *bool `json:"alwaysFormatResultValueAsList,omitempty"`
	DetectResultValueType *string `json:"detectResultValueType,omitempty"`
}

type _Formula Formula

// NewFormula instantiates a new Formula object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormula(formulaText string) *Formula {
	this := Formula{}
	this.FormulaText = formulaText
	return &this
}

// NewFormulaWithDefaults instantiates a new Formula object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormulaWithDefaults() *Formula {
	this := Formula{}
	return &this
}

// GetFormulaText returns the FormulaText field value
func (o *Formula) GetFormulaText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FormulaText
}

// GetFormulaTextOk returns a tuple with the FormulaText field value
// and a boolean to check if the value has been set.
func (o *Formula) GetFormulaTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormulaText, true
}

// SetFormulaText sets field value
func (o *Formula) SetFormulaText(v string) {
	o.FormulaText = v
}


// GetAlwaysFormatResultValueAsList returns the AlwaysFormatResultValueAsList field value if set, zero value otherwise.
func (o *Formula) GetAlwaysFormatResultValueAsList() bool {
	if o == nil || IsNil(o.AlwaysFormatResultValueAsList) {
		var ret bool
		return ret
	}
	return *o.AlwaysFormatResultValueAsList
}

// GetAlwaysFormatResultValueAsListOk returns a tuple with the AlwaysFormatResultValueAsList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Formula) GetAlwaysFormatResultValueAsListOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysFormatResultValueAsList) {
		return nil, false
	}
	return o.AlwaysFormatResultValueAsList, true
}

// HasAlwaysFormatResultValueAsList returns a boolean if a field has been set.
func (o *Formula) HasAlwaysFormatResultValueAsList() bool {
	if o != nil && !IsNil(o.AlwaysFormatResultValueAsList) {
		return true
	}

	return false
}

// SetAlwaysFormatResultValueAsList gets a reference to the given bool and assigns it to the AlwaysFormatResultValueAsList field.
func (o *Formula) SetAlwaysFormatResultValueAsList(v bool) {
	o.AlwaysFormatResultValueAsList = &v
}

// GetDetectResultValueType returns the DetectResultValueType field value if set, zero value otherwise.
func (o *Formula) GetDetectResultValueType() string {
	if o == nil || IsNil(o.DetectResultValueType) {
		var ret string
		return ret
	}
	return *o.DetectResultValueType
}

// GetDetectResultValueTypeOk returns a tuple with the DetectResultValueType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Formula) GetDetectResultValueTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DetectResultValueType) {
		return nil, false
	}
	return o.DetectResultValueType, true
}

// HasDetectResultValueType returns a boolean if a field has been set.
func (o *Formula) HasDetectResultValueType() bool {
	if o != nil && !IsNil(o.DetectResultValueType) {
		return true
	}

	return false
}

// SetDetectResultValueType gets a reference to the given string and assigns it to the DetectResultValueType field.
func (o *Formula) SetDetectResultValueType(v string) {
	o.DetectResultValueType = &v
}

func (o Formula) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Formula) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["formulaText"] = o.FormulaText
	if !IsNil(o.AlwaysFormatResultValueAsList) {
		toSerialize["alwaysFormatResultValueAsList"] = o.AlwaysFormatResultValueAsList
	}
	if !IsNil(o.DetectResultValueType) {
		toSerialize["detectResultValueType"] = o.DetectResultValueType
	}
	return toSerialize, nil
}

func (o *Formula) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"formulaText",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varFormula := _Formula{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFormula)

	if err != nil {
		return err
	}

	*o = Formula(varFormula)

	return err
}

type NullableFormula struct {
	value *Formula
	isSet bool
}

func (v NullableFormula) Get() *Formula {
	return v.value
}

func (v *NullableFormula) Set(val *Formula) {
	v.value = val
	v.isSet = true
}

func (v NullableFormula) IsSet() bool {
	return v.isSet
}

func (v *NullableFormula) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormula(val *Formula) *NullableFormula {
	return &NullableFormula{value: val, isSet: true}
}

func (v NullableFormula) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormula) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


