/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
)

// checks if the FileInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileInfoResponse{}

// FileInfoResponse struct for FileInfoResponse
type FileInfoResponse struct {
	Id *string `json:"id,omitempty"`
	OriginalName *string `json:"originalName,omitempty"`
	ContentType *string `json:"contentType,omitempty"`
	Size *int64 `json:"size,omitempty"`
	ThumbnailId *string `json:"thumbnailId,omitempty"`
}

// NewFileInfoResponse instantiates a new FileInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileInfoResponse() *FileInfoResponse {
	this := FileInfoResponse{}
	return &this
}

// NewFileInfoResponseWithDefaults instantiates a new FileInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileInfoResponseWithDefaults() *FileInfoResponse {
	this := FileInfoResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FileInfoResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfoResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FileInfoResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FileInfoResponse) SetId(v string) {
	o.Id = &v
}

// GetOriginalName returns the OriginalName field value if set, zero value otherwise.
func (o *FileInfoResponse) GetOriginalName() string {
	if o == nil || IsNil(o.OriginalName) {
		var ret string
		return ret
	}
	return *o.OriginalName
}

// GetOriginalNameOk returns a tuple with the OriginalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfoResponse) GetOriginalNameOk() (*string, bool) {
	if o == nil || IsNil(o.OriginalName) {
		return nil, false
	}
	return o.OriginalName, true
}

// HasOriginalName returns a boolean if a field has been set.
func (o *FileInfoResponse) HasOriginalName() bool {
	if o != nil && !IsNil(o.OriginalName) {
		return true
	}

	return false
}

// SetOriginalName gets a reference to the given string and assigns it to the OriginalName field.
func (o *FileInfoResponse) SetOriginalName(v string) {
	o.OriginalName = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *FileInfoResponse) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfoResponse) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *FileInfoResponse) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *FileInfoResponse) SetContentType(v string) {
	o.ContentType = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *FileInfoResponse) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfoResponse) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *FileInfoResponse) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *FileInfoResponse) SetSize(v int64) {
	o.Size = &v
}

// GetThumbnailId returns the ThumbnailId field value if set, zero value otherwise.
func (o *FileInfoResponse) GetThumbnailId() string {
	if o == nil || IsNil(o.ThumbnailId) {
		var ret string
		return ret
	}
	return *o.ThumbnailId
}

// GetThumbnailIdOk returns a tuple with the ThumbnailId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfoResponse) GetThumbnailIdOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbnailId) {
		return nil, false
	}
	return o.ThumbnailId, true
}

// HasThumbnailId returns a boolean if a field has been set.
func (o *FileInfoResponse) HasThumbnailId() bool {
	if o != nil && !IsNil(o.ThumbnailId) {
		return true
	}

	return false
}

// SetThumbnailId gets a reference to the given string and assigns it to the ThumbnailId field.
func (o *FileInfoResponse) SetThumbnailId(v string) {
	o.ThumbnailId = &v
}

func (o FileInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OriginalName) {
		toSerialize["originalName"] = o.OriginalName
	}
	if !IsNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.ThumbnailId) {
		toSerialize["thumbnailId"] = o.ThumbnailId
	}
	return toSerialize, nil
}

type NullableFileInfoResponse struct {
	value *FileInfoResponse
	isSet bool
}

func (v NullableFileInfoResponse) Get() *FileInfoResponse {
	return v.value
}

func (v *NullableFileInfoResponse) Set(val *FileInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFileInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFileInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileInfoResponse(val *FileInfoResponse) *NullableFileInfoResponse {
	return &NullableFileInfoResponse{value: val, isSet: true}
}

func (v NullableFileInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


