/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
)

// checks if the BulkExecutionTriggerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkExecutionTriggerRequest{}

// BulkExecutionTriggerRequest struct for BulkExecutionTriggerRequest
type BulkExecutionTriggerRequest struct {
	AutomationIds []string `json:"automationIds,omitempty"`
	Await *bool `json:"await,omitempty"`
}

// NewBulkExecutionTriggerRequest instantiates a new BulkExecutionTriggerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkExecutionTriggerRequest() *BulkExecutionTriggerRequest {
	this := BulkExecutionTriggerRequest{}
	return &this
}

// NewBulkExecutionTriggerRequestWithDefaults instantiates a new BulkExecutionTriggerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkExecutionTriggerRequestWithDefaults() *BulkExecutionTriggerRequest {
	this := BulkExecutionTriggerRequest{}
	return &this
}

// GetAutomationIds returns the AutomationIds field value if set, zero value otherwise.
func (o *BulkExecutionTriggerRequest) GetAutomationIds() []string {
	if o == nil || IsNil(o.AutomationIds) {
		var ret []string
		return ret
	}
	return o.AutomationIds
}

// GetAutomationIdsOk returns a tuple with the AutomationIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkExecutionTriggerRequest) GetAutomationIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AutomationIds) {
		return nil, false
	}
	return o.AutomationIds, true
}

// HasAutomationIds returns a boolean if a field has been set.
func (o *BulkExecutionTriggerRequest) HasAutomationIds() bool {
	if o != nil && !IsNil(o.AutomationIds) {
		return true
	}

	return false
}

// SetAutomationIds gets a reference to the given []string and assigns it to the AutomationIds field.
func (o *BulkExecutionTriggerRequest) SetAutomationIds(v []string) {
	o.AutomationIds = v
}

// GetAwait returns the Await field value if set, zero value otherwise.
func (o *BulkExecutionTriggerRequest) GetAwait() bool {
	if o == nil || IsNil(o.Await) {
		var ret bool
		return ret
	}
	return *o.Await
}

// GetAwaitOk returns a tuple with the Await field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkExecutionTriggerRequest) GetAwaitOk() (*bool, bool) {
	if o == nil || IsNil(o.Await) {
		return nil, false
	}
	return o.Await, true
}

// HasAwait returns a boolean if a field has been set.
func (o *BulkExecutionTriggerRequest) HasAwait() bool {
	if o != nil && !IsNil(o.Await) {
		return true
	}

	return false
}

// SetAwait gets a reference to the given bool and assigns it to the Await field.
func (o *BulkExecutionTriggerRequest) SetAwait(v bool) {
	o.Await = &v
}

func (o BulkExecutionTriggerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkExecutionTriggerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutomationIds) {
		toSerialize["automationIds"] = o.AutomationIds
	}
	if !IsNil(o.Await) {
		toSerialize["await"] = o.Await
	}
	return toSerialize, nil
}

type NullableBulkExecutionTriggerRequest struct {
	value *BulkExecutionTriggerRequest
	isSet bool
}

func (v NullableBulkExecutionTriggerRequest) Get() *BulkExecutionTriggerRequest {
	return v.value
}

func (v *NullableBulkExecutionTriggerRequest) Set(val *BulkExecutionTriggerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkExecutionTriggerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkExecutionTriggerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkExecutionTriggerRequest(val *BulkExecutionTriggerRequest) *NullableBulkExecutionTriggerRequest {
	return &NullableBulkExecutionTriggerRequest{value: val, isSet: true}
}

func (v NullableBulkExecutionTriggerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkExecutionTriggerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


