/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateGrid type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGrid{}

// CreateGrid struct for CreateGrid
type CreateGrid struct {
	Id *string `json:"id,omitempty" validate:"regexp=^\\\\w+$"`
	Name string `json:"name"`
	TemplateGridId *string `json:"templateGridId,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	RecordIdentifierType string `json:"recordIdentifierType"`
	Columns []CreateColumn `json:"columns,omitempty"`
}

type _CreateGrid CreateGrid

// NewCreateGrid instantiates a new CreateGrid object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGrid(name string, recordIdentifierType string) *CreateGrid {
	this := CreateGrid{}
	this.Name = name
	this.RecordIdentifierType = recordIdentifierType
	return &this
}

// NewCreateGridWithDefaults instantiates a new CreateGrid object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGridWithDefaults() *CreateGrid {
	this := CreateGrid{}
	var recordIdentifierType string = "recordId"
	this.RecordIdentifierType = recordIdentifierType
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateGrid) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGrid) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateGrid) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateGrid) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *CreateGrid) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateGrid) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateGrid) SetName(v string) {
	o.Name = v
}


// GetTemplateGridId returns the TemplateGridId field value if set, zero value otherwise.
func (o *CreateGrid) GetTemplateGridId() string {
	if o == nil || IsNil(o.TemplateGridId) {
		var ret string
		return ret
	}
	return *o.TemplateGridId
}

// GetTemplateGridIdOk returns a tuple with the TemplateGridId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGrid) GetTemplateGridIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateGridId) {
		return nil, false
	}
	return o.TemplateGridId, true
}

// HasTemplateGridId returns a boolean if a field has been set.
func (o *CreateGrid) HasTemplateGridId() bool {
	if o != nil && !IsNil(o.TemplateGridId) {
		return true
	}

	return false
}

// SetTemplateGridId gets a reference to the given string and assigns it to the TemplateGridId field.
func (o *CreateGrid) SetTemplateGridId(v string) {
	o.TemplateGridId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateGrid) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGrid) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateGrid) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CreateGrid) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetRecordIdentifierType returns the RecordIdentifierType field value
func (o *CreateGrid) GetRecordIdentifierType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordIdentifierType
}

// GetRecordIdentifierTypeOk returns a tuple with the RecordIdentifierType field value
// and a boolean to check if the value has been set.
func (o *CreateGrid) GetRecordIdentifierTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordIdentifierType, true
}

// SetRecordIdentifierType sets field value
func (o *CreateGrid) SetRecordIdentifierType(v string) {
	o.RecordIdentifierType = v
}

// GetDefaultRecordIdentifierType returns the default value "recordId" of the RecordIdentifierType field.
func (o *CreateGrid) GetDefaultRecordIdentifierType() interface{}  {
	return "recordId"
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *CreateGrid) GetColumns() []CreateColumn {
	if o == nil || IsNil(o.Columns) {
		var ret []CreateColumn
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGrid) GetColumnsOk() ([]CreateColumn, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *CreateGrid) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []CreateColumn and assigns it to the Columns field.
func (o *CreateGrid) SetColumns(v []CreateColumn) {
	o.Columns = v
}

func (o CreateGrid) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGrid) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.TemplateGridId) {
		toSerialize["templateGridId"] = o.TemplateGridId
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if _, exists := toSerialize["recordIdentifierType"]; !exists {
		toSerialize["recordIdentifierType"] = o.GetDefaultRecordIdentifierType()
	}
	toSerialize["recordIdentifierType"] = o.RecordIdentifierType
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	return toSerialize, nil
}

func (o *CreateGrid) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"recordIdentifierType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
		"recordIdentifierType": o.GetDefaultRecordIdentifierType,
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varCreateGrid := _CreateGrid{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateGrid)

	if err != nil {
		return err
	}

	*o = CreateGrid(varCreateGrid)

	return err
}

type NullableCreateGrid struct {
	value *CreateGrid
	isSet bool
}

func (v NullableCreateGrid) Get() *CreateGrid {
	return v.value
}

func (v *NullableCreateGrid) Set(val *CreateGrid) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGrid) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGrid) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGrid(val *CreateGrid) *NullableCreateGrid {
	return &NullableCreateGrid{value: val, isSet: true}
}

func (v NullableCreateGrid) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGrid) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


