/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
)

// checks if the SetRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetRecord{}

// SetRecord struct for SetRecord
type SetRecord struct {
	Id *string `json:"id,omitempty"`
	Cells []SetCell `json:"cells,omitempty"`
	MarkUpdatedCellsWithMTFlag *bool `json:"markUpdatedCellsWithMTFlag,omitempty"`
	Path *string `json:"path,omitempty"`
}

// NewSetRecord instantiates a new SetRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetRecord() *SetRecord {
	this := SetRecord{}
	return &this
}

// NewSetRecordWithDefaults instantiates a new SetRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetRecordWithDefaults() *SetRecord {
	this := SetRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SetRecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetRecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SetRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SetRecord) SetId(v string) {
	o.Id = &v
}

// GetCells returns the Cells field value if set, zero value otherwise.
func (o *SetRecord) GetCells() []SetCell {
	if o == nil || IsNil(o.Cells) {
		var ret []SetCell
		return ret
	}
	return o.Cells
}

// GetCellsOk returns a tuple with the Cells field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetRecord) GetCellsOk() ([]SetCell, bool) {
	if o == nil || IsNil(o.Cells) {
		return nil, false
	}
	return o.Cells, true
}

// HasCells returns a boolean if a field has been set.
func (o *SetRecord) HasCells() bool {
	if o != nil && !IsNil(o.Cells) {
		return true
	}

	return false
}

// SetCells gets a reference to the given []SetCell and assigns it to the Cells field.
func (o *SetRecord) SetCells(v []SetCell) {
	o.Cells = v
}

// GetMarkUpdatedCellsWithMTFlag returns the MarkUpdatedCellsWithMTFlag field value if set, zero value otherwise.
func (o *SetRecord) GetMarkUpdatedCellsWithMTFlag() bool {
	if o == nil || IsNil(o.MarkUpdatedCellsWithMTFlag) {
		var ret bool
		return ret
	}
	return *o.MarkUpdatedCellsWithMTFlag
}

// GetMarkUpdatedCellsWithMTFlagOk returns a tuple with the MarkUpdatedCellsWithMTFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetRecord) GetMarkUpdatedCellsWithMTFlagOk() (*bool, bool) {
	if o == nil || IsNil(o.MarkUpdatedCellsWithMTFlag) {
		return nil, false
	}
	return o.MarkUpdatedCellsWithMTFlag, true
}

// HasMarkUpdatedCellsWithMTFlag returns a boolean if a field has been set.
func (o *SetRecord) HasMarkUpdatedCellsWithMTFlag() bool {
	if o != nil && !IsNil(o.MarkUpdatedCellsWithMTFlag) {
		return true
	}

	return false
}

// SetMarkUpdatedCellsWithMTFlag gets a reference to the given bool and assigns it to the MarkUpdatedCellsWithMTFlag field.
func (o *SetRecord) SetMarkUpdatedCellsWithMTFlag(v bool) {
	o.MarkUpdatedCellsWithMTFlag = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *SetRecord) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetRecord) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *SetRecord) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *SetRecord) SetPath(v string) {
	o.Path = &v
}

func (o SetRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Cells) {
		toSerialize["cells"] = o.Cells
	}
	if !IsNil(o.MarkUpdatedCellsWithMTFlag) {
		toSerialize["markUpdatedCellsWithMTFlag"] = o.MarkUpdatedCellsWithMTFlag
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	return toSerialize, nil
}

type NullableSetRecord struct {
	value *SetRecord
	isSet bool
}

func (v NullableSetRecord) Get() *SetRecord {
	return v.value
}

func (v *NullableSetRecord) Set(val *SetRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableSetRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableSetRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetRecord(val *SetRecord) *NullableSetRecord {
	return &NullableSetRecord{value: val, isSet: true}
}

func (v NullableSetRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


