/*
Gridly API

Gridly API documentation

API version: 3.21.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
)

// UpdateMetadata struct for UpdateMetadata
type UpdateMetadata struct {
	Data *map[string]string `json:"data,omitempty"`
}

// NewUpdateMetadata instantiates a new UpdateMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMetadata() *UpdateMetadata {
	this := UpdateMetadata{}
	return &this
}

// NewUpdateMetadataWithDefaults instantiates a new UpdateMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMetadataWithDefaults() *UpdateMetadata {
	this := UpdateMetadata{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateMetadata) GetData() map[string]string {
	if o == nil || o.Data == nil {
		var ret map[string]string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMetadata) GetDataOk() (*map[string]string, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateMetadata) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]string and assigns it to the Data field.
func (o *UpdateMetadata) SetData(v map[string]string) {
	o.Data = &v
}

func (o UpdateMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateMetadata struct {
	value *UpdateMetadata
	isSet bool
}

func (v NullableUpdateMetadata) Get() *UpdateMetadata {
	return v.value
}

func (v *NullableUpdateMetadata) Set(val *UpdateMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMetadata(val *UpdateMetadata) *NullableUpdateMetadata {
	return &NullableUpdateMetadata{value: val, isSet: true}
}

func (v NullableUpdateMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


