/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
)

// checks if the LQAModelCategoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LQAModelCategoryResponse{}

// LQAModelCategoryResponse struct for LQAModelCategoryResponse
type LQAModelCategoryResponse struct {
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	SubCategories []LQAModelSubCategoryResponse `json:"subCategories,omitempty"`
}

// NewLQAModelCategoryResponse instantiates a new LQAModelCategoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLQAModelCategoryResponse() *LQAModelCategoryResponse {
	this := LQAModelCategoryResponse{}
	return &this
}

// NewLQAModelCategoryResponseWithDefaults instantiates a new LQAModelCategoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLQAModelCategoryResponseWithDefaults() *LQAModelCategoryResponse {
	this := LQAModelCategoryResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LQAModelCategoryResponse) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LQAModelCategoryResponse) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LQAModelCategoryResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *LQAModelCategoryResponse) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LQAModelCategoryResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LQAModelCategoryResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LQAModelCategoryResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LQAModelCategoryResponse) SetName(v string) {
	o.Name = &v
}

// GetSubCategories returns the SubCategories field value if set, zero value otherwise.
func (o *LQAModelCategoryResponse) GetSubCategories() []LQAModelSubCategoryResponse {
	if o == nil || IsNil(o.SubCategories) {
		var ret []LQAModelSubCategoryResponse
		return ret
	}
	return o.SubCategories
}

// GetSubCategoriesOk returns a tuple with the SubCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LQAModelCategoryResponse) GetSubCategoriesOk() ([]LQAModelSubCategoryResponse, bool) {
	if o == nil || IsNil(o.SubCategories) {
		return nil, false
	}
	return o.SubCategories, true
}

// HasSubCategories returns a boolean if a field has been set.
func (o *LQAModelCategoryResponse) HasSubCategories() bool {
	if o != nil && !IsNil(o.SubCategories) {
		return true
	}

	return false
}

// SetSubCategories gets a reference to the given []LQAModelSubCategoryResponse and assigns it to the SubCategories field.
func (o *LQAModelCategoryResponse) SetSubCategories(v []LQAModelSubCategoryResponse) {
	o.SubCategories = v
}

func (o LQAModelCategoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LQAModelCategoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SubCategories) {
		toSerialize["subCategories"] = o.SubCategories
	}
	return toSerialize, nil
}

type NullableLQAModelCategoryResponse struct {
	value *LQAModelCategoryResponse
	isSet bool
}

func (v NullableLQAModelCategoryResponse) Get() *LQAModelCategoryResponse {
	return v.value
}

func (v *NullableLQAModelCategoryResponse) Set(val *LQAModelCategoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLQAModelCategoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLQAModelCategoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLQAModelCategoryResponse(val *LQAModelCategoryResponse) *NullableLQAModelCategoryResponse {
	return &NullableLQAModelCategoryResponse{value: val, isSet: true}
}

func (v NullableLQAModelCategoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLQAModelCategoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


