/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"fmt"
)

// ExportTransMemFormat the model 'ExportTransMemFormat'
type ExportTransMemFormat string

// List of ExportTransMemFormat
const (
	EXPORTTRANSMEMFORMAT_TMX ExportTransMemFormat = "tmx"
	EXPORTTRANSMEMFORMAT_CSV ExportTransMemFormat = "csv"
	EXPORTTRANSMEMFORMAT_XLSX ExportTransMemFormat = "xlsx"
)

// All allowed values of ExportTransMemFormat enum
var AllowedExportTransMemFormatEnumValues = []ExportTransMemFormat{
	"tmx",
	"csv",
	"xlsx",
}

func (v *ExportTransMemFormat) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExportTransMemFormat(value)
	for _, existing := range AllowedExportTransMemFormatEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExportTransMemFormat", value)
}

// NewExportTransMemFormatFromValue returns a pointer to a valid ExportTransMemFormat
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExportTransMemFormatFromValue(v string) (*ExportTransMemFormat, error) {
	ev := ExportTransMemFormat(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExportTransMemFormat: valid values are %v", v, AllowedExportTransMemFormatEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExportTransMemFormat) IsValid() bool {
	for _, existing := range AllowedExportTransMemFormatEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ExportTransMemFormat value
func (v ExportTransMemFormat) Ptr() *ExportTransMemFormat {
	return &v
}

type NullableExportTransMemFormat struct {
	value *ExportTransMemFormat
	isSet bool
}

func (v NullableExportTransMemFormat) Get() *ExportTransMemFormat {
	return v.value
}

func (v *NullableExportTransMemFormat) Set(val *ExportTransMemFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableExportTransMemFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableExportTransMemFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportTransMemFormat(val *ExportTransMemFormat) *NullableExportTransMemFormat {
	return &NullableExportTransMemFormat{value: val, isSet: true}
}

func (v NullableExportTransMemFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportTransMemFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

