/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SelectionOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelectionOption{}

// SelectionOption struct for SelectionOption
type SelectionOption struct {
	Color *string `json:"color,omitempty"`
	Value string `json:"value"`
}

type _SelectionOption SelectionOption

// NewSelectionOption instantiates a new SelectionOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectionOption(value string) *SelectionOption {
	this := SelectionOption{}
	this.Value = value
	return &this
}

// NewSelectionOptionWithDefaults instantiates a new SelectionOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectionOptionWithDefaults() *SelectionOption {
	this := SelectionOption{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *SelectionOption) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelectionOption) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *SelectionOption) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *SelectionOption) SetColor(v string) {
	o.Color = &v
}

// GetValue returns the Value field value
func (o *SelectionOption) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SelectionOption) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SelectionOption) SetValue(v string) {
	o.Value = v
}


func (o SelectionOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelectionOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *SelectionOption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varSelectionOption := _SelectionOption{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSelectionOption)

	if err != nil {
		return err
	}

	*o = SelectionOption(varSelectionOption)

	return err
}

type NullableSelectionOption struct {
	value *SelectionOption
	isSet bool
}

func (v NullableSelectionOption) Get() *SelectionOption {
	return v.value
}

func (v *NullableSelectionOption) Set(val *SelectionOption) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectionOption) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectionOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectionOption(val *SelectionOption) *NullableSelectionOption {
	return &NullableSelectionOption{value: val, isSet: true}
}

func (v NullableSelectionOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectionOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


