/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Reference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Reference{}

// Reference struct for Reference
type Reference struct {
	GridId string `json:"gridId"`
	BranchId *string `json:"branchId,omitempty"`
	ColumnId string `json:"columnId"`
	Type *string `json:"type,omitempty"`
	SelectionType *string `json:"selectionType,omitempty"`
}

type _Reference Reference

// NewReference instantiates a new Reference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReference(gridId string, columnId string) *Reference {
	this := Reference{}
	this.GridId = gridId
	this.ColumnId = columnId
	return &this
}

// NewReferenceWithDefaults instantiates a new Reference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferenceWithDefaults() *Reference {
	this := Reference{}
	return &this
}

// GetGridId returns the GridId field value
func (o *Reference) GetGridId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GridId
}

// GetGridIdOk returns a tuple with the GridId field value
// and a boolean to check if the value has been set.
func (o *Reference) GetGridIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GridId, true
}

// SetGridId sets field value
func (o *Reference) SetGridId(v string) {
	o.GridId = v
}


// GetBranchId returns the BranchId field value if set, zero value otherwise.
func (o *Reference) GetBranchId() string {
	if o == nil || IsNil(o.BranchId) {
		var ret string
		return ret
	}
	return *o.BranchId
}

// GetBranchIdOk returns a tuple with the BranchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reference) GetBranchIdOk() (*string, bool) {
	if o == nil || IsNil(o.BranchId) {
		return nil, false
	}
	return o.BranchId, true
}

// HasBranchId returns a boolean if a field has been set.
func (o *Reference) HasBranchId() bool {
	if o != nil && !IsNil(o.BranchId) {
		return true
	}

	return false
}

// SetBranchId gets a reference to the given string and assigns it to the BranchId field.
func (o *Reference) SetBranchId(v string) {
	o.BranchId = &v
}

// GetColumnId returns the ColumnId field value
func (o *Reference) GetColumnId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ColumnId
}

// GetColumnIdOk returns a tuple with the ColumnId field value
// and a boolean to check if the value has been set.
func (o *Reference) GetColumnIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ColumnId, true
}

// SetColumnId sets field value
func (o *Reference) SetColumnId(v string) {
	o.ColumnId = v
}


// GetType returns the Type field value if set, zero value otherwise.
func (o *Reference) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reference) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Reference) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Reference) SetType(v string) {
	o.Type = &v
}

// GetSelectionType returns the SelectionType field value if set, zero value otherwise.
func (o *Reference) GetSelectionType() string {
	if o == nil || IsNil(o.SelectionType) {
		var ret string
		return ret
	}
	return *o.SelectionType
}

// GetSelectionTypeOk returns a tuple with the SelectionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reference) GetSelectionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SelectionType) {
		return nil, false
	}
	return o.SelectionType, true
}

// HasSelectionType returns a boolean if a field has been set.
func (o *Reference) HasSelectionType() bool {
	if o != nil && !IsNil(o.SelectionType) {
		return true
	}

	return false
}

// SetSelectionType gets a reference to the given string and assigns it to the SelectionType field.
func (o *Reference) SetSelectionType(v string) {
	o.SelectionType = &v
}

func (o Reference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Reference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gridId"] = o.GridId
	if !IsNil(o.BranchId) {
		toSerialize["branchId"] = o.BranchId
	}
	toSerialize["columnId"] = o.ColumnId
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.SelectionType) {
		toSerialize["selectionType"] = o.SelectionType
	}
	return toSerialize, nil
}

func (o *Reference) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gridId",
		"columnId",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varReference := _Reference{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReference)

	if err != nil {
		return err
	}

	*o = Reference(varReference)

	return err
}

type NullableReference struct {
	value *Reference
	isSet bool
}

func (v NullableReference) Get() *Reference {
	return v.value
}

func (v *NullableReference) Set(val *Reference) {
	v.value = val
	v.isSet = true
}

func (v NullableReference) IsSet() bool {
	return v.isSet
}

func (v *NullableReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReference(val *Reference) *NullableReference {
	return &NullableReference{value: val, isSet: true}
}

func (v NullableReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


