/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LengthLimitSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LengthLimitSetting{}

// LengthLimitSetting struct for LengthLimitSetting
type LengthLimitSetting struct {
	Value *int32 `json:"value,omitempty"`
	Unit string `json:"unit"`
	UseSourceTextLength *bool `json:"useSourceTextLength,omitempty"`
}

type _LengthLimitSetting LengthLimitSetting

// NewLengthLimitSetting instantiates a new LengthLimitSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLengthLimitSetting(unit string) *LengthLimitSetting {
	this := LengthLimitSetting{}
	this.Unit = unit
	return &this
}

// NewLengthLimitSettingWithDefaults instantiates a new LengthLimitSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLengthLimitSettingWithDefaults() *LengthLimitSetting {
	this := LengthLimitSetting{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *LengthLimitSetting) GetValue() int32 {
	if o == nil || IsNil(o.Value) {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LengthLimitSetting) GetValueOk() (*int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *LengthLimitSetting) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *LengthLimitSetting) SetValue(v int32) {
	o.Value = &v
}

// GetUnit returns the Unit field value
func (o *LengthLimitSetting) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *LengthLimitSetting) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *LengthLimitSetting) SetUnit(v string) {
	o.Unit = v
}


// GetUseSourceTextLength returns the UseSourceTextLength field value if set, zero value otherwise.
func (o *LengthLimitSetting) GetUseSourceTextLength() bool {
	if o == nil || IsNil(o.UseSourceTextLength) {
		var ret bool
		return ret
	}
	return *o.UseSourceTextLength
}

// GetUseSourceTextLengthOk returns a tuple with the UseSourceTextLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LengthLimitSetting) GetUseSourceTextLengthOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSourceTextLength) {
		return nil, false
	}
	return o.UseSourceTextLength, true
}

// HasUseSourceTextLength returns a boolean if a field has been set.
func (o *LengthLimitSetting) HasUseSourceTextLength() bool {
	if o != nil && !IsNil(o.UseSourceTextLength) {
		return true
	}

	return false
}

// SetUseSourceTextLength gets a reference to the given bool and assigns it to the UseSourceTextLength field.
func (o *LengthLimitSetting) SetUseSourceTextLength(v bool) {
	o.UseSourceTextLength = &v
}

func (o LengthLimitSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LengthLimitSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	toSerialize["unit"] = o.Unit
	if !IsNil(o.UseSourceTextLength) {
		toSerialize["useSourceTextLength"] = o.UseSourceTextLength
	}
	return toSerialize, nil
}

func (o *LengthLimitSetting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unit",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varLengthLimitSetting := _LengthLimitSetting{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLengthLimitSetting)

	if err != nil {
		return err
	}

	*o = LengthLimitSetting(varLengthLimitSetting)

	return err
}

type NullableLengthLimitSetting struct {
	value *LengthLimitSetting
	isSet bool
}

func (v NullableLengthLimitSetting) Get() *LengthLimitSetting {
	return v.value
}

func (v *NullableLengthLimitSetting) Set(val *LengthLimitSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableLengthLimitSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableLengthLimitSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLengthLimitSetting(val *LengthLimitSetting) *NullableLengthLimitSetting {
	return &NullableLengthLimitSetting{value: val, isSet: true}
}

func (v NullableLengthLimitSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLengthLimitSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


