/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
)

// checks if the LQAModelProjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LQAModelProjectResponse{}

// LQAModelProjectResponse struct for LQAModelProjectResponse
type LQAModelProjectResponse struct {
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewLQAModelProjectResponse instantiates a new LQAModelProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLQAModelProjectResponse() *LQAModelProjectResponse {
	this := LQAModelProjectResponse{}
	return &this
}

// NewLQAModelProjectResponseWithDefaults instantiates a new LQAModelProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLQAModelProjectResponseWithDefaults() *LQAModelProjectResponse {
	this := LQAModelProjectResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LQAModelProjectResponse) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LQAModelProjectResponse) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LQAModelProjectResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *LQAModelProjectResponse) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LQAModelProjectResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LQAModelProjectResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LQAModelProjectResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LQAModelProjectResponse) SetName(v string) {
	o.Name = &v
}

func (o LQAModelProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LQAModelProjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableLQAModelProjectResponse struct {
	value *LQAModelProjectResponse
	isSet bool
}

func (v NullableLQAModelProjectResponse) Get() *LQAModelProjectResponse {
	return v.value
}

func (v *NullableLQAModelProjectResponse) Set(val *LQAModelProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLQAModelProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLQAModelProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLQAModelProjectResponse(val *LQAModelProjectResponse) *NullableLQAModelProjectResponse {
	return &NullableLQAModelProjectResponse{value: val, isSet: true}
}

func (v NullableLQAModelProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLQAModelProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


