/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
)

// checks if the ExecutionTriggerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecutionTriggerRequest{}

// ExecutionTriggerRequest struct for ExecutionTriggerRequest
type ExecutionTriggerRequest struct {
	Await *bool `json:"await,omitempty"`
}

// NewExecutionTriggerRequest instantiates a new ExecutionTriggerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecutionTriggerRequest() *ExecutionTriggerRequest {
	this := ExecutionTriggerRequest{}
	return &this
}

// NewExecutionTriggerRequestWithDefaults instantiates a new ExecutionTriggerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutionTriggerRequestWithDefaults() *ExecutionTriggerRequest {
	this := ExecutionTriggerRequest{}
	return &this
}

// GetAwait returns the Await field value if set, zero value otherwise.
func (o *ExecutionTriggerRequest) GetAwait() bool {
	if o == nil || IsNil(o.Await) {
		var ret bool
		return ret
	}
	return *o.Await
}

// GetAwaitOk returns a tuple with the Await field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecutionTriggerRequest) GetAwaitOk() (*bool, bool) {
	if o == nil || IsNil(o.Await) {
		return nil, false
	}
	return o.Await, true
}

// HasAwait returns a boolean if a field has been set.
func (o *ExecutionTriggerRequest) HasAwait() bool {
	if o != nil && !IsNil(o.Await) {
		return true
	}

	return false
}

// SetAwait gets a reference to the given bool and assigns it to the Await field.
func (o *ExecutionTriggerRequest) SetAwait(v bool) {
	o.Await = &v
}

func (o ExecutionTriggerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecutionTriggerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Await) {
		toSerialize["await"] = o.Await
	}
	return toSerialize, nil
}

type NullableExecutionTriggerRequest struct {
	value *ExecutionTriggerRequest
	isSet bool
}

func (v NullableExecutionTriggerRequest) Get() *ExecutionTriggerRequest {
	return v.value
}

func (v *NullableExecutionTriggerRequest) Set(val *ExecutionTriggerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutionTriggerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutionTriggerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutionTriggerRequest(val *ExecutionTriggerRequest) *NullableExecutionTriggerRequest {
	return &NullableExecutionTriggerRequest{value: val, isSet: true}
}

func (v NullableExecutionTriggerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutionTriggerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


