/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateView{}

// CreateView struct for CreateView
type CreateView struct {
	Name string `json:"name"`
	GridId string `json:"gridId"`
	Columns []AddViewColumn `json:"columns,omitempty"`
}

type _CreateView CreateView

// NewCreateView instantiates a new CreateView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateView(name string, gridId string) *CreateView {
	this := CreateView{}
	this.Name = name
	this.GridId = gridId
	return &this
}

// NewCreateViewWithDefaults instantiates a new CreateView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateViewWithDefaults() *CreateView {
	this := CreateView{}
	return &this
}

// GetName returns the Name field value
func (o *CreateView) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateView) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateView) SetName(v string) {
	o.Name = v
}


// GetGridId returns the GridId field value
func (o *CreateView) GetGridId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GridId
}

// GetGridIdOk returns a tuple with the GridId field value
// and a boolean to check if the value has been set.
func (o *CreateView) GetGridIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GridId, true
}

// SetGridId sets field value
func (o *CreateView) SetGridId(v string) {
	o.GridId = v
}


// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *CreateView) GetColumns() []AddViewColumn {
	if o == nil || IsNil(o.Columns) {
		var ret []AddViewColumn
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateView) GetColumnsOk() ([]AddViewColumn, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *CreateView) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []AddViewColumn and assigns it to the Columns field.
func (o *CreateView) SetColumns(v []AddViewColumn) {
	o.Columns = v
}

func (o CreateView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["gridId"] = o.GridId
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	return toSerialize, nil
}

func (o *CreateView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"gridId",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varCreateView := _CreateView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateView)

	if err != nil {
		return err
	}

	*o = CreateView(varCreateView)

	return err
}

type NullableCreateView struct {
	value *CreateView
	isSet bool
}

func (v NullableCreateView) Get() *CreateView {
	return v.value
}

func (v *NullableCreateView) Set(val *CreateView) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateView) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateView(val *CreateView) *NullableCreateView {
	return &NullableCreateView{value: val, isSet: true}
}

func (v NullableCreateView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


