/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteFile{}

// DeleteFile struct for DeleteFile
type DeleteFile struct {
	Ids []string `json:"ids"`
}

type _DeleteFile DeleteFile

// NewDeleteFile instantiates a new DeleteFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteFile(ids []string) *DeleteFile {
	this := DeleteFile{}
	this.Ids = ids
	return &this
}

// NewDeleteFileWithDefaults instantiates a new DeleteFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteFileWithDefaults() *DeleteFile {
	this := DeleteFile{}
	return &this
}

// GetIds returns the Ids field value
func (o *DeleteFile) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *DeleteFile) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *DeleteFile) SetIds(v []string) {
	o.Ids = v
}


func (o DeleteFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *DeleteFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varDeleteFile := _DeleteFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteFile)

	if err != nil {
		return err
	}

	*o = DeleteFile(varDeleteFile)

	return err
}

type NullableDeleteFile struct {
	value *DeleteFile
	isSet bool
}

func (v NullableDeleteFile) Get() *DeleteFile {
	return v.value
}

func (v *NullableDeleteFile) Set(val *DeleteFile) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteFile) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteFile(val *DeleteFile) *NullableDeleteFile {
	return &NullableDeleteFile{value: val, isSet: true}
}

func (v NullableDeleteFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


