/*
Gridly API

Gridly API documentation

API version: 6.13.0
Contact: support@gridly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gridly

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBranch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBranch{}

// CreateBranch struct for CreateBranch
type CreateBranch struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	CustomProperties map[string]map[string]interface{} `json:"customProperties,omitempty"`
	InheritGroupAccess *bool `json:"inheritGroupAccess,omitempty"`
	InheritAutomation *bool `json:"inheritAutomation,omitempty"`
	ViewId *string `json:"viewId,omitempty"`
}

type _CreateBranch CreateBranch

// NewCreateBranch instantiates a new CreateBranch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBranch(name string) *CreateBranch {
	this := CreateBranch{}
	this.Name = name
	return &this
}

// NewCreateBranchWithDefaults instantiates a new CreateBranch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBranchWithDefaults() *CreateBranch {
	this := CreateBranch{}
	return &this
}

// GetName returns the Name field value
func (o *CreateBranch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateBranch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateBranch) SetName(v string) {
	o.Name = v
}


// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateBranch) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBranch) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateBranch) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateBranch) SetDescription(v string) {
	o.Description = &v
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise.
func (o *CreateBranch) GetCustomProperties() map[string]map[string]interface{} {
	if o == nil || IsNil(o.CustomProperties) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBranch) GetCustomPropertiesOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomProperties) {
		return map[string]map[string]interface{}{}, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *CreateBranch) HasCustomProperties() bool {
	if o != nil && !IsNil(o.CustomProperties) {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given map[string]map[string]interface{} and assigns it to the CustomProperties field.
func (o *CreateBranch) SetCustomProperties(v map[string]map[string]interface{}) {
	o.CustomProperties = v
}

// GetInheritGroupAccess returns the InheritGroupAccess field value if set, zero value otherwise.
func (o *CreateBranch) GetInheritGroupAccess() bool {
	if o == nil || IsNil(o.InheritGroupAccess) {
		var ret bool
		return ret
	}
	return *o.InheritGroupAccess
}

// GetInheritGroupAccessOk returns a tuple with the InheritGroupAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBranch) GetInheritGroupAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.InheritGroupAccess) {
		return nil, false
	}
	return o.InheritGroupAccess, true
}

// HasInheritGroupAccess returns a boolean if a field has been set.
func (o *CreateBranch) HasInheritGroupAccess() bool {
	if o != nil && !IsNil(o.InheritGroupAccess) {
		return true
	}

	return false
}

// SetInheritGroupAccess gets a reference to the given bool and assigns it to the InheritGroupAccess field.
func (o *CreateBranch) SetInheritGroupAccess(v bool) {
	o.InheritGroupAccess = &v
}

// GetInheritAutomation returns the InheritAutomation field value if set, zero value otherwise.
func (o *CreateBranch) GetInheritAutomation() bool {
	if o == nil || IsNil(o.InheritAutomation) {
		var ret bool
		return ret
	}
	return *o.InheritAutomation
}

// GetInheritAutomationOk returns a tuple with the InheritAutomation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBranch) GetInheritAutomationOk() (*bool, bool) {
	if o == nil || IsNil(o.InheritAutomation) {
		return nil, false
	}
	return o.InheritAutomation, true
}

// HasInheritAutomation returns a boolean if a field has been set.
func (o *CreateBranch) HasInheritAutomation() bool {
	if o != nil && !IsNil(o.InheritAutomation) {
		return true
	}

	return false
}

// SetInheritAutomation gets a reference to the given bool and assigns it to the InheritAutomation field.
func (o *CreateBranch) SetInheritAutomation(v bool) {
	o.InheritAutomation = &v
}

// GetViewId returns the ViewId field value if set, zero value otherwise.
func (o *CreateBranch) GetViewId() string {
	if o == nil || IsNil(o.ViewId) {
		var ret string
		return ret
	}
	return *o.ViewId
}

// GetViewIdOk returns a tuple with the ViewId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBranch) GetViewIdOk() (*string, bool) {
	if o == nil || IsNil(o.ViewId) {
		return nil, false
	}
	return o.ViewId, true
}

// HasViewId returns a boolean if a field has been set.
func (o *CreateBranch) HasViewId() bool {
	if o != nil && !IsNil(o.ViewId) {
		return true
	}

	return false
}

// SetViewId gets a reference to the given string and assigns it to the ViewId field.
func (o *CreateBranch) SetViewId(v string) {
	o.ViewId = &v
}

func (o CreateBranch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBranch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CustomProperties) {
		toSerialize["customProperties"] = o.CustomProperties
	}
	if !IsNil(o.InheritGroupAccess) {
		toSerialize["inheritGroupAccess"] = o.InheritGroupAccess
	}
	if !IsNil(o.InheritAutomation) {
		toSerialize["inheritAutomation"] = o.InheritAutomation
	}
	if !IsNil(o.ViewId) {
		toSerialize["viewId"] = o.ViewId
	}
	return toSerialize, nil
}

func (o *CreateBranch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varCreateBranch := _CreateBranch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBranch)

	if err != nil {
		return err
	}

	*o = CreateBranch(varCreateBranch)

	return err
}

type NullableCreateBranch struct {
	value *CreateBranch
	isSet bool
}

func (v NullableCreateBranch) Get() *CreateBranch {
	return v.value
}

func (v *NullableCreateBranch) Set(val *CreateBranch) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBranch) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBranch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBranch(val *CreateBranch) *NullableCreateBranch {
	return &NullableCreateBranch{value: val, isSet: true}
}

func (v NullableCreateBranch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBranch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


