name: Gridly Go

on:
  push:
    branches: [ main ]
    tags: 
      - '*'

jobs:

  build:
    name: Full SDK and tools test
    # Tests for actively maintained Go versions.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version:
          - 1.16.x
          - 1.17.x
    env:
      RELEASE_VERSION: ""
    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # - name: Archive Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     # Artifact name
    #     name: com.gridly.go-sdk
    #     # A file, directory or wildcard pattern that describes what to upload
    #     path: .*
    #     retention-days: 1
    #     if-no-files-found: error
    - name: Get version
      run: |
        VER=$(cat VERSION)
        echo "RELEASE_VERSION=$VER" >> $GITHUB_ENV      
    - name: Github Release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        tag_name: ${{ env.RELEASE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
